// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/nikhilnarayanan623/random-school-generator-grpc/api-gateway/pkg/api"
	"github.com/nikhilnarayanan623/random-school-generator-grpc/api-gateway/pkg/api/handler"
	"github.com/nikhilnarayanan623/random-school-generator-grpc/api-gateway/pkg/client"
	"github.com/nikhilnarayanan623/random-school-generator-grpc/api-gateway/pkg/config"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	schoolClient, err := client.NewSchoolClient(cfg)
	if err != nil {
		return nil, err
	}
	schoolHandler := handler.NewSchoolHandler(schoolClient)
	server := api.NewServerHTTP(cfg, schoolHandler)
	return server, nil
}
