// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"school-service/pkg/api"
	"school-service/pkg/api/service"
	"school-service/pkg/config"
	"school-service/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*api.Server, error) {
	schoolUseCase := usecase.NewSchoolUseCase()
	schoolServiceServer := service.NewSchoolService(schoolUseCase)
	server, err := api.NewServerGRPC(cfg, schoolServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
